language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  matrix:
    -
#    - DEPENDENCIES=--prefer-lowest

cache:
  directories:
    - .composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - alias composer=composer\ --no-interaction && composer selfupdate
  - composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

before_script:
  - echo 'max_execution_time = 180' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
   - vendor/bin/grumphp run